# Generated by Django 5.0.4 on 2024-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
